// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package golang

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "golang", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
<<<<<<< HEAD
	return "eJzkV9tu40YMffdXEH7Kook/wEAX2Lqo+9CmBdIWBYrCoCVKmmYuwpCyrb8vZiQ5jiJp7WwCF1s92SOBPOfwMuQdPFK9hNxptPkMQJRoWsJ8HQ/mM4CUOPGqFOXsEj7OAACal2BcWmmaAXDhvGwSZzOVLyFDzeHUkyZkWsKWBMNXJKJszkv4a86s57cwL0TK+d8zgEyRTnkZrd+BRUMnmMIjdRmOvKvK9mQA13M7p7boUO7QH4+H7I3abJ4XFvr0uqcP4RRGYlKtLD1712F5pHrvfNp7N4EoPL8V1BkFl4EUimHtoPQu92iABb3AXkmxeCFJQVh+iSDB9YmrYA6UzZw3GD4PgjmmFLZ1q93iKxBvEFieDGLqa3kGojX6LeYEidOaEnEeuDIGfb3ofTqk0ykkcYJ6U2LFfb2m8Z2BsZEu2If1CqILSCvfBN3tyINWGYkyUdTSu4SY+/inOJzysDzsv6Wg3bFBvIYFAHzfIVcW7gdgPhc0cZWVUUFH0Jyvp63MlnyQbb2CPTIUWJZkKR3HZekgmzzZaGXUxciaYl3CthYaEvoc5Pd0kC5fg457pXWLG/YFWfiRsPyktUvgY1NiaIKK45SSstpkHqO5UUaZdjjE9xzIP7TGg9CrX3+HmKtV26vWq3Fk71dPPyHLy3Li8EvZHKQgMM4qcfFvSV65gaQ4r6bGkhjesKxgFZy0mdzrEUdOirvEmWD0hJsrM4l6TP9LYI/1tUsxT0cCzulwcE44LuF2Rrc7BWbw8O5y/4yHr1fsi9TG3ZjXt1P70458mC7+f4oPjm1cs1C/pbx6dAvXXDet3e4LlRTNtRrvcbcVVJZSyLwzreNXjXRXuOGblthwGeIBN1yZ0On/PBweaoYtabf/MH6JdjauQOUPhTFODzXfTjBaxGVmwzXDt81PlWqCb9rftmIap8eCyeMVuH0X6XRTTEQBGMYuFOdvAW0apgimC7PyiVi7sl0jbg23DgCIiwPRLw+fKfCWfhik3rTKT+y+dj8z0caQHF+6Stwfd4jWx3hEM0+DEXk7CNHDVCv4hxJ5Dwj9faoNGaWdz89seldL8iegN7QjC6oRMf0AUnhX5YWrJGZ/t2SPEzma+g+QCe3HOoGapOEDN4yGABma3RC3bkcTt0bowFfjoWz0D1yincicsFXurorSOnt3RLqY/RsAAP//4jNGiQ=="
=======
	return "eJzkV9tu40YMffdXEH7Kook/wEAX2Lqo+9CmBdIWBYrCoCVKmmYuwpCyrb8vZiQ5jiJp7WwCF1s9KSOHPOfwMuQdPFK9hNxptPkMQJRoWsJ8HQ/mM4CUOPGqFOXsEj7OAACaj2BcWmmaAXDhvGwSZzOVLyFDzeHUkyZkWsKWBMOvSETZnJfw15xZz29hXoiU879nAJkinfIyWr8Di4ZOMIVH6jIceVeV7ckArud2Tm3RodyhPx4P2Ru12TwvLPTpdU8fwimMxKRaWXr2rcPySPXe+bT3bQJReH4rqDMKLgMpFLe6Qeld7tEAC3qBvZJi8UKWgrD8ElGC+567YBKUzZw3GP4lCOeYUtjWrYaLr0TEQXB5Moirr+kZqNbot5gTJE5rSsR54MoY9PWi99MhrU4hiRPUmxIr7ms2je8MjI18wT6sVxBdQFr5JvBuRx60ykiUicKW3iXE3Mc/xeGUh+Vh/y0F7Y7N4jUsAOD7DrmycD8A87mgiausjAo6guZ8PW1ltuSDbOsV7JGhwLIkS+k4LksH2eTJRiujLkbWFOwStrXQkNDnIL+ng3T5GnTcK61b3LAvyMKPhOUnrV0CH5syQxNUHKeUlNUm8xjNjTLKtMMhvudA/qE1HoRe/fo7xFyt2n61Xo0je796+glZXpYThzdlc5CCwDirxMU/S/LKDSTFeTU1lsTwhmUFq+CkzeRejzhyUtwlzgSjJ9xcmUnUY/pfAnusr12KeToScE6Hg3PCcQm3M7rdKTCDh3eX+2c8fL1iX6Q27sa8vp3an3bkw3Tx/1N8cGzjmoX6LeXVo1u45rpp7XZfqKRortV4j7utoLKUQuadaR2/aqS7wg3ftMSGyxAPuOHKhE7/5+HwUDNsSbv9h/FLtLNxBSp/KIxxeqj5doLRIi40G64Zvm1eVaoJvmnfbcU0To8Fk8crcPsu0ummmIgCMIxdKM7fAto0TBFMF2blE7F2bbtG3BpuHQAQFweiXx4+U+At/TBIvWmVn9h97X5moo0hOb50lbg/7hCtj/GIZp4GI/J2EKKHqVbwDyXyHhD6+1QbMko7n5/Z9K6W5E9Ab2hHFlQjYvoBpPCuygtXScz+bskeJ3I09R8gE9qPdQI1ScMHbhgNATI0uyFu3Y4mbo3Qga/GQ9noH7hEO5E5YavcXRWldfbuiHQx+zcAAP//h95Lzw=="
>>>>>>> aa82756e2ff04055bd5c7678a03abc815bec4b32
}
